Refactor Faction UI system
drtshock/Factions pull request #1194
Opened 2019-04-09 16:16 UTC by Dariasc

Rewrite the old ugly UI system, now contains:

- Dynamic items that change depending on User state
- Cleaner and less duplicate code

2019-04-09 16:19 UTC, Dariasc commented
I still need to do some testing with the changes I've made.
Would love any more ideas to clean this up a bit more.

Might be a good idea to JavaDoc this a bit, was a bit hard for me to wrap my head around the changes I made

2019-04-20 23:49 UTC, Dariasc commented
Implemented a Back system currently only in use by Action.

Updated config to use new `Materials.JSON` data

![perms](https://i.imgur.com/jq2QlPN.gif)

2019-04-28 22:37 UTC, drtshock requested changes

2019-04-28 22:37 UTC, drtshock commented on src/main/java/com/massivecraft/factions/zcore/ui/FactionUI.java
> +            return;
Log an error here?

2019-04-28 22:37 UTC, drtshock commented on src/main/java/com/massivecraft/factions/zcore/ui/FactionUI.java
> +            return;
Also log an error here if we're unable to build a GUI.

2019-04-28 22:59 UTC, drtshock approved these changes

2019-05-03 01:46 UTC, merged